//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverZone.Domain.Impl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public System.Guid Id { get; set; }
        public System.Guid ShoppingCartId { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
